### ISSUE TITLE
"Getting Started" is broken

### ISSUE THREAD

**Issue by Steve-A-Orr** [HueyNemud/hyrax-dev-docker#1]
I'm on macOS Sierra (10.12.6) using Docker CE (18.03.1-ce-mac65 24312) and have followed your _Getting Started_ steps unsuccessfully. Unfortunately, I'm new to both Hyrax and Docker so my troubleshooting techniques in these tools are slim.

It fails at the end of the last step of the **Build** phase, such that my attempt at running the container using the first command in the **Run** phase fails. Here are my screen captures--

The beginning commands:
![screen shot 2018-05-15 at 15 30 38](https://user-images.githubusercontent.com/4119409/40087644-48767d56-5858-11e8-8494-4abd4454834a.png)

The resulting error and failure of next command:
![screen shot 2018-05-15 at 15 43 10](https://user-images.githubusercontent.com/4119409/40087677-82dc3166-5858-11e8-90d7-9ad3f56cdd47.png)

My attempt to create the example directory, before I re-ran the build:
![screen shot 2018-05-15 at 15 47 01](https://user-images.githubusercontent.com/4119409/40087701-a8cbf708-5858-11e8-8c9f-d57506430e3b.png)

The contents of the cloned repository directory:
![screen shot 2018-05-15 at 16 00 06](https://user-images.githubusercontent.com/4119409/40087833-2c887f58-5859-11e8-86f2-d8c4b1b7f0c6.png)

I'm unsure really what I should do next to get your container code to run, as I assume it should. Might you have some advice for me?

**Comment by HueyNemud** [comment]
Hi Steven, 

For some reason, the .gemspec used by one of the Hyrax dependency is using non-ascii chars, which was causing bundle to crash.
The image locale is now set to en_US-UTF-8, which should fix the bug.
